version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.27
    # I don't want this to always restart during development
    # restart: always
    ports:
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            database: ${PG_DB}
            user: ${PG_USER}
            password: ${PG_PWD}
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres:10.7
    # I don't want this to always restart during development
    # restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
