version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: fandem-io-test.c2ilmknaee16.eu-west-1.rds.amazonaws.com
            database: fandem_io_test
            user: demonstrator
            password: V1qc57PgEFoYkFD
            rawAccess: true
            port: '4309'
            migrations: true